### ISSUE TITLE
Sub directory under a domain is not effective.

### ISSUE THREAD

**Issue by deepraining** [Justinidlerz/html-webpack-prefix-plugin#3]
I make a prefix, as follows

```
{
     prefix: 'http://www.example.com/dir/'
}
```

As a result, `/dir/` is hidden in html.

```
<script src="http://www.example.com/path/to/production/js/file"></script>
```

Sometimes, it's extremely useful when deply multi projects to a single domain.

**Comment by Justinidlerz** [comment]
This plugin will be join your setting prefix to matched relative url like so:
`http://www.example.com/dir/` + `./path/to/production/js/file`  
=> `http://www.example.com/dir/path/to/production/js/file`

But when your url is start with `/`, the plugin will follow node module `url` to resolve your url, it like so:
`http://www.example.com/dir/` + `/path/to/production/js/file`   
=> `http://www.example.com/path/to/production/js/file`

Hope it can helps you.

**Comment by deepraining** [comment]
Maybe I can use gulp to solve this problem. Thanks!
